add cicd varaibles for nfs and workers

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -68,10 +68,19 @@ connect-to-cluster-job:
         echo "❌ Error: worker_ips.txt is empty! Terraform output might be incorrect."
         exit 1
       fi
-    - echo "pushing cluster ip to gitlab"
-    # - curl --request PUT --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" --header "Content-Type: application/json" --data "{\"key\": \"CLUSTER_IP\", \"value\": \"$(cat cluster_ip.txt)\"}" "https://gitlab.com/api/v4/groups/YOUR_GROUP_ID/variables/CLUSTER_IP"
+    - jq -r '.outputs.ec2_nfs_server_private_ip.value' terraform.tfstate > nfs_server_ip.txt
+    - cat nfs_server_ip.txt
+    - |
+      if [ ! -s nfs_server_ip.txt ]; then
+        echo "❌ Error: nfs_server_ip.txt is empty! Terraform output might be incorrect."
+        exit 1
+      fi   - echo "pushing cluster ip to gitlab"
+    - |
+      curl --request PUT --header "PRIVATE-TOKEN: $CI_ACCESS_TOKEN_FULL" --header "Content-Type: application/json" --data "{\"key\": \"NFS_SERVER_IP\", \"value\": \"$(cat nfs_server_ip.txt)\"}" "https://gitlab.com/api/v4/groups/$GROUP_ID/variables/NFS_SERVER_IP"
     - |
       curl --request PUT --header "PRIVATE-TOKEN: $CI_ACCESS_TOKEN_FULL" --header "Content-Type: application/json" --data "{\"key\": \"CLUSTER_IP\", \"value\": \"$(cat cluster_ip.txt)\"}" "https://gitlab.com/api/v4/groups/$GROUP_ID/variables/CLUSTER_IP"
+    - |
+      curl --request PUT --header "PRIVATE-TOKEN: $CI_ACCESS_TOKEN_FULL" --header "Content-Type: application/json" --data "{\"key\": \"WORKER_IPS\", \"value\": \"$(cat worker_ips.txt)\"}" "https://gitlab.com/api/v4/groups/$GROUP_ID/variables/WORKER_IPS"
     # - cd ..
     # - chmod u+x ./init.sh ./transform_worker_ips.sh
     # - ./transform_worker_ips.sh terraform/worker_ips.txt > terraform/worker_ips_transformed.txt
